version: "3"
services:
  api:
    container_name: main_api
    build: ./API
    ports:
      - "800:8080"
      - "801:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=801
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - .\API\https:/https/ 
    networks:
      - net
    depends_on:
      - pgdb
  front:
    container_name: main_front
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - net
    depends_on:
      - api
  pgdb:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  net:
    driver: bridge
volumes:
  pgdata: